#!/usr/bin/env python3
import argparse
import json
import subprocess
from pathlib import Path


def paragraph(text):
    return " ".join(text.strip().split())


def render_list(title, values):
    if not values:
        return []

    lines = [f"{title}:"]
    lines.extend(f"- `{value}`" for value in values)
    lines.append("")
    return lines


def render_item(item):
    lines = [
        f"## {item['name']}",
        "",
        f"Layer: `{item['layer']}`",
        "",
        paragraph(item["description"]),
        "",
    ]

    if item.get("useWhen"):
        lines.extend([
            f"Guidance: {paragraph(item['useWhen'])}",
            "",
        ])

    lines.extend(render_list("Includes", item.get("includes", [])))
    lines.extend(render_list("Hardware", item.get("hardware", [])))
    lines.extend(render_list("System software", item.get("systemSoftware", [])))
    lines.extend(render_list("User software", item.get("userSoftware", [])))
    lines.extend(render_list("Home software", item.get("homeSoftware", [])))

    return lines


def render_page(page):
    lines = [
        f"# {page['title']}",
        "",
        "<!-- Generated by scripts/generate-catalog-docs.py. Edit lib/catalog-docs.nix instead. -->",
        "",
        paragraph(page["intro"]),
        "",
    ]

    for item in page["items"]:
        lines.extend(render_item(item))

    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate catalog Markdown docs.")
    parser.add_argument("--flake", default="path:.", help="Flake reference to evaluate.")
    parser.add_argument("--out-dir", default="docs", help="Directory for generated Markdown.")
    args = parser.parse_args()

    result = subprocess.run(
        ["nix", "eval", "--json", f"{args.flake}#lib.catalogDocs.pages"],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    pages = json.loads(result.stdout)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for page in pages:
        target = out_dir / page["file"]
        target.write_text(render_page(page), encoding="utf-8")


if __name__ == "__main__":
    main()
